### PR TITLE
Allow separate fits per group for `fit_optim_split()`

### LINKED ISSUE #39: Separate splitting dates for each group when fit_optim_split() takes groups into account?
I am preparing the worked example for the incidence paper. The following code reproduces the problem.

```
# prepare the data
library(outbreaks)

girardot <- data.frame(date = rep(zika_girardot_2015$date, zika_girardot_2015$cases))
girardot$setting <- "Girardot"
sanandres <- data.frame(date = rep(zika_sanandres_2015$date, zika_sanandres_2015$cases))
sanandres$setting <- "San Andres"
zika_colombia_2015 <- rbind(girardot, sanandres)

# weekly incidence by setting
library(incidence)
i.7.setting <- incidence(zika_colombia_2015$date, interval = 7, 
                         groups = zika_colombia_2015$setting)
plot(i.7.setting, stack = FALSE, border = "white")

# fit the log-linear regression models by setting
best.fit2 <- fit_optim_split(i.7.setting)$fit
best.fit2
plot(i.7.setting, fit=best.fit2, border="white")
```
The resulting plot is as follows

image

I think the problem occurred because the epidemic in San Andres was earlier than in Girardot.  In this case, `fit_optim_split()` should separately return splitting dates for each group.

### PR DESCRIPTION
**Pull request by zkamvar**
This implements an option `separate_split` in `fit_optim_split()` that allows the groups to have separate split dates to fix #39. I've also raised the coverage to >97%

Changes
========

* `fit_optim_split()` now gains a `separate_split` argument that will determine
  the optimal split separately for groups.

* A new class, `incidence_fit_list`, has been implemented to store and summarise
  `incidence_fit` objects within a nested list. This is the class returned by
  in the `$fit` element of `fit_optim_split()`.

* `find_peak()` gains the argument `pool`, giving the user the choice to find the 
  peak per group or pooled.

* `get_counts()` returns the matrix of case counts for each date.

* `get_fit()` returns a list of `incidence_fit` objects from an
  `incidence_fit_list` object.

* `get_info()` returns information stored in the `$info` element of an 
  `incidence_fit`/`incidence_fit_list` object.

### CODE REVIEW

**Comment by zkamvar** [comment]
If there are no objections, I will merge this PR tomorrow.

**Comment by caijun** [comment]
@thibautjombart is more familiar with the implementation of `fit_optim_split()` than me, perhaps requesting review from him is better.

**Comment by caijun** [comment]
I commented under https://github.com/reconhub/incidence/issues/39, it perfectly solved my issue and I like the way in which the returning objects are organized, e.g. ``best.fit2$fit$`San Andres`$before``. The access is so convenient. 👍

**Comment by zkamvar** [comment]
I'll consider that good enough. And if @thibautjombart doesn't like this change, then he shouldn't have made me maintainer :stuck_out_tongue_winking_eye:

**Pull request merged**
