### PR TITLE
add more tests

### PR DESCRIPTION
**Pull request by caijun**
@thibautjombart I have added some tests to test-conversions.R and ran the following command,

```
> covr::package_coverage()
incidence Coverage: 0.00%
R/conversion.R: 0.00%
R/fit.R: 0.00%
R/incidence.R: 0.00%
R/palettes.R: 0.00%
R/plot.R: 0.00%
R/pool.R: 0.00%
R/subset.R: 0.00%
```
I don't know why the test coverage is zero on my local PC. What's the right approach to know the test coverage?

### CODE REVIEW

**Comment by caijun** [comment]
I will continue to add test until the test coverage of incidence package is 100%. So please don't merge this PR temporally.

**Comment by caijun** [comment]
The test coverage of incidence package has increased to 100%. You can merge the isoweek branch into master and release the new version of incidence package on CRAN.

**Comment by thibautjombart** [comment]
Thanks! You might have found it already, but the trick for `covr` to run with `skip_on_cran()` is to set an envir. var:
```
Sys.setenv("NOT_CRAN" = "true")
```
Thanks @richfitz for this tip (I asked the same question last week). 

@caijun It looks all good to me. Will submit new version to CRAN - shout if there's any last minute changes you want to make. Thanks for your contribution!

**Comment by caijun** [comment]
Thanks for this tip. Currently I don't have any further changes. I think it's ready to submit new version to CRAN.

**Pull request merged**
