### PR TITLE
add an argument x.labels_iso_week to plot.incidence() and unit test for incidence()

### PR DESCRIPTION
**Pull request by caijun**
@thibautjombart I have added the argument `x.labels_iso_week` to plot.incidence() and unit test for constructing ISO week-based weekly incidence. The documents including README (where you can see the figures with x axis labels of isoweeks.) have been updated.

Currently, we can label the x axis tick marks with isoweeks when plotting ISO week-based weekly incidence without adding fit. I think it is complicated to make plot.incidence() support isoweeks labels while adding fit.  Because fit is calculated based on dates. Besides, the tests for plot.incidence() failed on my local Mac PC after adding `x.labels_iso_week` as an argument to `plot.incidence()`, which I think should  succeed. So, I haven't added any further test for the new version of `plot.incidence()`. Maybe we need a better approach to test `plot.incidence()`.

### CODE REVIEW

**Comment by thibautjombart** [comment]
Thanks for carrying this forward. Some thoughts:

* **tests failing**: this is to be expected, what the tests actually test is that the content of the ggplot2 object matches a given reference; so if the plot changes, the tests will fail. The course of action so far would be:

1. check the new figures are OK
2. remove the previous reference files
3. run `test()` again, which will save new figures as reference

*  **adding fit to `plot.incidence` with `x.labels_iso_week=TRUE`**: this should work; the dates used for prediction in the fit objects are supposed to match the `$dates` of *incidence* objects; it is set there:
https://github.com/reconhub/incidence/blob/master/R/fit.R#L317-L318

Implementation hinges on how the iso weeks are treated:

a. as mere labels added to plot on plotting time; if this is the case, then there should be no problem
b. treated as new x-axis values; in this case we need to change the line referred above when using iso week

Makes sense?

ps: we are using *snake_case* throughout so how about `labels_iso_week`?

**Comment by caijun** [comment]
I think it's easy to fix the failure of testing plot.incidence() according to your suggestion.

The iso weeks are treated as mere labels added to plot on plotting integer value (I converted the dates into integers). Thanks for your hint, I just find the conversion from dates into integers is not necessary. I figure out a solution and I will give it a try.

**Comment by thibautjombart** [comment]
Great, let me know if I can help.

**Comment by caijun** [comment]
Now plot.incidence() can label x axis tick marks with isoweeks when adding fit. Could you help to review the code? Thank you very much.

**Comment by thibautjombart** [comment]
Great, I'll review the code this afternoon.

**Comment by thibautjombart** [comment]
Merged manually. Thanks!

**Pull request closed without merging**
